#!/bin/bash

for i in {0..20}
do
    ./gauss_eliminate 2048 4 >> 2048_elements
done

echo " " >> 2048_elements

for i in {0..20}
do
    ./gauss_eliminate 2048 8 >> 2048_elements
done

echo " " >> 2048_elements

for i in {0..20}
do
    ./gauss_eliminate 2048 16 >> 2048_elements
done

echo " " >> 2048_elements

for i in {0..20}
do
    ./gauss_eliminate 2048 32 >> 2048_elements
done

echo " " >> 2048_elements